version: '3'

networks:
 net:
  driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - net
  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/app
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - net
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - '4200:80'
    networks:
      - net
